### PR TITLE
Display user customised HDMI label

### PR DESCRIPTION
**Pull request by RogerSelwyn**
Used call to getCurrentExternalInputsStatus to get HDMI labels when available. Then convert HDMI title to label when set by user on the TV. Converts back to HDMI title for selecting source.

This change tries to retrieve the label information even when on standby due to a bug in the TV that generates a 500 error which can occur when TV is switched on. Once it has been retrieved it will not try to refresh until HA is restarted.

### CODE REVIEW

**Comment by gerard33** [comment]
Thanks for your PR.

> Then convert HDMI title to label when set by user on the TV. Converts back to HDMI title for selecting source.

This is not a breaking change? Will an automation with the HDMI title still work?

**Comment by RogerSelwyn** [comment]
I’d need to check that out, I don’t think using the original will fail. However using the converted one in an automation  may fail, because you can’t be sure the custom labels will always be discovered on HA start, since access to the information depends on the 500 error not occurring.

**Comment by gerard33** [comment]
Ok, otherwise we can make this a configuration setting, which defaults to not using the label. That way it's not a breaking change and can be used by people when they want to.

**Comment by RogerSelwyn** [comment]
I can update the PR to do that. Let me give you a definite answer tomorrow. Then work from there.

**Comment by gerard33** [comment]
Great. But I would not like to introduce the 500 error for people not using this. Or is that not happening anymore? Otherwise adding a config for this would be the best way forward.

**Comment by RogerSelwyn** [comment]
It handles the 500 error, and just won't do the conversion to the custom value at startup if the call to the TV returns 500. So no error will be bubbled back to the logs..

**Comment by RogerSelwyn** [comment]
I've just checked by using Developer/Service and you can use either the custom label or the actual source name (i.e. either Sky Q or HDMI 1) to change source, so existing automations won't break. I didn't run a formal automation, I use Node Red and don't have that setup in my dev environment, but the service calls are the same as initiated via the Developer dialogue.

As I said before, for absolute reliability 'HDMI 1' should be used, because that is fixed, whilst the label may change and may not be discoverable depending on the state of the TV, if HA was restarted whilst on a CEC source it will get a 500 error (which is in no way presented to the user, it just won't have the labels converted). The labels will get converted when the TV is switched off next, on the regular refresh.

I'll add to the PR a config variable to enable/disable the feature.

**Comment by RogerSelwyn** [comment]
I've now added a configuration value 'user_labels' defaulted to False. Also updated relevant readme/info.

**Comment by gerard33** [comment]
Thanks. Will have a look at this asap.

**Comment by gerard33** [comment]
Thanks for your PR!

**Pull request merged**
