### PR TITLE
Update lib version

### PR DESCRIPTION
**Pull request by gerard33**

### CODE REVIEW

**Comment by gerard33** [comment]
@rchl any other updates planned for the sony-bravia-psk lib or the custom component related to https://github.com/gerard33/sony_bravia_psk/pull/18?

**Comment by rchl** [comment]
Hi @gerard33 . Yes, I have worked on getting https://github.com/custom-components/media_player.braviatv_psk/pull/42 adapted to the latest master. I will sunroom something later in the evening.

**Comment by gerard33** [comment]
Great 👍🏻 
No hurries.

**Comment by rchl** [comment]
I have no more changes to the sony-bravia-psk lib though.

**Pull request merged**
