### PR TITLE
Add media_player.bravia_command service for sending arbitrary commands

### PR DESCRIPTION
**Pull request by rchl**
As some TVs support many more commands that the existing API exposes
(for example Assistant, Subtitle, Action Menu, Picture Menu, etc.),
let user send any command she wants. Useful for creating virtual remote
control for example.

I don't think "services.yaml" file gets picked up but probably would
when having this as an official component.

### CODE REVIEW

**Comment by gerard33** [comment]
Thanks for your PR.
Have you tried adding the new commands you want to use to [this]( https://github.com/custom-components/media_player.braviatv_psk/blob/master/custom_components/braviatv_psk/media_player.py#L53-L60) which can be used like mentioned [here](https://community.home-assistant.io/t/sony-bravia-tv-component-with-pre-shared-key/30698/253?u=gerard33)?

**Comment by rchl** [comment]
But would that allow me to add arbitrary commands there? The command IDs that are currently supported are exported from `homeassistant.components.media_player` and it wouldn't make sense to all add of them there.

Also, there would be *a lot* of new commands if I would want to add all that I want to use (currently using about 28). And that's probably just half of what is supported by my TV.

**Comment by gerard33** [comment]
I prefer to have it added to `PLAY_MEDIA_OPTIONS`. That list is already in place and already being used. So please add the items you want to have there in a PR, preferaly already grouped for the logic and overview of that list.

**Comment by gerard33** [comment]
Had another look at your PR and agree that your solution is way more flexible than `PLAY_MEDIA_OPTIONS`. Will do some testing and if all went well merge this.

**Comment by gerard33** [comment]
Thanks for the PR!

**Pull request merged**
