### PR TITLE
Update to work as an async Integration

### PR DESCRIPTION
**Pull request by RogerSelwyn**
Sync methods changed to work in async manner where possible. Calls to Sony_bravia_psk achieved using hass_async_ass_executor_job.

### CODE REVIEW

**Comment by gerard33** [comment]
Thanks for the PR. Will have a look at it asap and can release it as a beta for testing.

**Comment by RogerSelwyn** [comment]
I think I've checked all the methods I changed. I've also run all the relevant services against it. Worth a double check though.

**Comment by gerard33** [comment]
I will merge the PR in the `dev_async` branch and will make a beta release for testing.

**Comment by rchl** [comment]
How to test beta?

Trying to add the link https://github.com/custom-components/media_player.braviatv_psk/tree/dev_async manually fails with:

Screenshot 2021-03-07 at 21 53 43

I guess I haven't tried removing the original repository yet but technically those are different repos so it's weird that it would be needed.

**Comment by RogerSelwyn** [comment]
Go to reinstall integration, it will then show you versions, and a toggle switch for betas.

**Comment by gerard33** [comment]
As Roger says, there is no need to add a custom repository nor to remove the current one.

**Comment by gerard33** [comment]
@RogerSelwyn I see some messages every now and then in the logs `Updating braviatv_psk media_player took longer than the scheduled update interval 0:00:10`
but definitely a lot less than before 👍

@rchl were you already able to do some testing?

**Comment by RogerSelwyn** [comment]
I agree, not perfect, but better.

**Comment by rchl** [comment]
@gerard33 it all appears to work for me just fine.

**Pull request merged**
